name: Deploy to Hostinger

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v5
      
    - name: Setup Node.js
      uses: actions/setup-node@v5
      with:
        node-version: '22'
        
    - name: Install Dependencies
      run: npm install
      
    - name: Build Project
      run: npm run build
      
    - name: Deploy build to prod branch
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        destination_branch: prod
        publish_branch: prod
        force_orphan: true
        user_name: github-actions
        user_email: github-actions@github.com
        
    - name: Sync files to Hostinger FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.4.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/
        server-dir: public_html/clientes/draclaudialima/
